// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tradgardsgolf.Infrastructure.Database;

#nullable disable

namespace Tradgardsgolf.Infrastructure.Migrations
{
    [DbContext(typeof(TradgardsgolfContext))]
    [Migration("20231221093123_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tradgardsgolf.Core.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtmCreated");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("intCreatedBy");

                    b.Property<int>("Holes")
                        .HasColumnType("int")
                        .HasColumnName("intHoles");

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("dblLatitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("dblLongitude");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("strName");

                    b.Property<DateTime?>("ScoreReset")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtmScoreReset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("course");
                });

            modelBuilder.Entity("Tradgardsgolf.Core.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtmCreated");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("strEmail");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("strKey");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("strName");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("strPassword");

                    b.HasKey("Id");

                    b.ToTable("player");
                });

            modelBuilder.Entity("Tradgardsgolf.Core.Entities.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("intCourseId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtmDate");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("round");
                });

            modelBuilder.Entity("Tradgardsgolf.Core.Entities.RoundScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Hole")
                        .HasColumnType("int")
                        .HasColumnName("intHole");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("intPlayerId");

                    b.Property<int>("RoundId")
                        .HasColumnType("int")
                        .HasColumnName("intRoundId");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("intScore");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RoundId");

                    b.ToTable("roundscore");
                });

            modelBuilder.Entity("Tradgardsgolf.Core.Entities.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("strName");

                    b.HasKey("Id");

                    b.ToTable("tournament");
                });

            modelBuilder.Entity("Tradgardsgolf.Core.Entities.TournamentCourseDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("intCourseId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtmDate");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int")
                        .HasColumnName("intTournamentId");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TournamentId");

                    b.ToTable("tournamentcoursedate");
                });

            modelBuilder.Entity("Tradgardsgolf.Core.Entities.TournamentRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoundId")
                        .HasColumnType("int")
                        .HasColumnName("intCourseId");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int")
                        .HasColumnName("intTournamentId");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.HasIndex("TournamentId");

                    b.ToTable("tournamentround");
                });

            modelBuilder.Entity("Tradgardsgolf.Core.Entities.Course", b =>
                {
                    b.HasOne("Tradgardsgolf.Core.Entities.Player", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Tradgardsgolf.Core.Entities.Round", b =>
                {
                    b.HasOne("Tradgardsgolf.Core.Entities.Course", "Course")
                        .WithMany("Rounds")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Tradgardsgolf.Core.Entities.RoundScore", b =>
                {
                    b.HasOne("Tradgardsgolf.Core.Entities.Player", "Player")
                        .WithMany("RoundScores")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tradgardsgolf.Core.Entities.Round", "Round")
                        .WithMany("RoundScores")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Tradgardsgolf.Core.Entities.TournamentCourseDate", b =>
                {
                    b.HasOne("Tradgardsgolf.Core.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tradgardsgolf.Core.Entities.Tournament", "Tournament")
                        .WithMany("TournamentCourseDates")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Tradgardsgolf.Core.Entities.TournamentRound", b =>
                {
                    b.HasOne("Tradgardsgolf.Core.Entities.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tradgardsgolf.Core.Entities.Tournament", "Tournament")
                        .WithMany("TournamentRounds")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Tradgardsgolf.Core.Entities.Course", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("Tradgardsgolf.Core.Entities.Player", b =>
                {
                    b.Navigation("RoundScores");
                });

            modelBuilder.Entity("Tradgardsgolf.Core.Entities.Round", b =>
                {
                    b.Navigation("RoundScores");
                });

            modelBuilder.Entity("Tradgardsgolf.Core.Entities.Tournament", b =>
                {
                    b.Navigation("TournamentCourseDates");

                    b.Navigation("TournamentRounds");
                });
#pragma warning restore 612, 618
        }
    }
}
