// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Tradgardsgolf.ApiClient.Authentication
{
    using Newtonsoft.Json;

    public partial class CredentialsModel
    {
        /// <summary>
        /// Initializes a new instance of the CredentialsModel class.
        /// </summary>
        public CredentialsModel() { }

        /// <summary>
        /// Initializes a new instance of the CredentialsModel class.
        /// </summary>
        public CredentialsModel(string email, string password)
        {
            Email = email;
            Password = password;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "password")]
        public string Password { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Email == null)
            {
                throw new ValidationException($"{nameof(Email)} can't be null");
            }
            if (Password == null)
            {
                throw new ValidationException($"{nameof(Password)} can't be null");
            }
        }
    }
}
