// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Tradgardsgolf.ApiClient.Authentication
{
    [System.Serializable]
    public class ValidationException : System.Exception
    {
        public ValidationException(string message) : base(message) { }
    }
}
