name: Main pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

  deploy_api:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "tradgardsgolf-api"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          docker_heroku_process_type: "web"
          usedocker: true
          docker_build_args: ENV
        env:
          ENV: api

  deploy_wasm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "tradgardsgolf"
          heroku_email:  ${{secrets.HEROKU_EMAIL}} 
          docker_heroku_process_type: "web"
          usedocker: true
          docker_build_args: ENV
        env:
          ENV: wasm
       
